export enum POKEMON_TYPES {
  'normal' = '../../../../../../assets/types/normal.svg',
  'fighting' = '../../../../../../assets/types/fighting.svg',
  'flying' = '../../../../../../assets/types/flying.svg',
  'poison' = '../../../../../../assets/types/poison.svg',
  'ground' = '../../../../../../assets/types/ground.svg',
  'rock' = '../../../../../../assets/types/rock.svg',
  'bug' = '../../../../../../assets/types/bug.svg',
  'ghost' = '../../../../../../assets/types/ghost.svg',
  'steel' = '../../../../../../assets/types/steel.svg',
  'fire' = '../../../../../../assets/types/fire.svg',
  'water' = '../../../../../../assets/types/water.svg',
  'grass' = '../../../../../../assets/types/grass.svg',
  'electric' = '../../../../../../assets/types/electric.svg',
  'psychic' = '../../../../../../assets/types/psychic.svg',
  'ice' = '../../../../../../assets/types/ice.svg',
  'dragon' = '../../../../../../assets/types/dragon.svg',
  'dark' = '../../../../../../assets/types/dark.svg',
  'fairy' = '../../../../../../assets/types/fairy.svg',
  'unknown' = '',
  'shadow' = ''
}